project_id = "memento"

[api]
schemas = ["public", "graphql_public", "memento"]

[db]
major_version = 17

[db.seed]
# Starter vocabulary is created by the application for each Telegram user.
enabled = false
