import type { VocabularyItem } from "./vocabulary.types";

export const starterVocabulary: VocabularyItem[] = [
  {
    id: 1,
    term: "reluctant",
    definition: "Unwilling or hesitant",
    status: "learning",
  },
  {
    id: 2,
    term: "meticulous",
    definition: "Very careful and precise",
    status: "learning",
  },
  {
    id: 3,
    term: "adamant",
    definition: "Unwilling to change one’s mind",
    status: "learning",
  },
  {
    id: 4,
    term: "eloquent",
    definition: "Fluent and persuasive",
    status: "learning",
  },
  {
    id: 5,
    term: "ubiquitous",
    definition: "Present or found everywhere",
    status: "learning",
  },
  {
    id: 6,
    term: "candid",
    definition: "Honest and straightforward",
    status: "learning",
  },
  {
    id: 7,
    term: "discern",
    definition: "Recognize something clearly",
    status: "learning",
  },
  {
    id: 8,
    term: "astute",
    definition: "Quick to understand situations",
    status: "learning",
  },
  {
    id: 9,
    term: "concise",
    definition: "Clear and brief",
    status: "learning",
  },
  {
    id: 10,
    term: "take into account",
    definition: "Consider when making a decision",
    status: "learning",
  },
  {
    id: 11,
    term: "prevalent",
    definition: "Common or widespread",
    status: "learning",
  },
  {
    id: 12,
    term: "ambiguous",
    definition: "Open to several meanings",
    status: "learning",
  },
  {
    id: 13,
    term: "pragmatic",
    definition: "Practical and realistic",
    status: "learning",
  },
  {
    id: 14,
    term: "elusive",
    definition: "Difficult to find or achieve",
    status: "learning",
  },
  {
    id: 15,
    term: "nuanced",
    definition: "Showing subtle differences",
    status: "learning",
  },
  {
    id: 16,
    term: "resilient",
    definition: "Quick to recover from difficulty",
    status: "learned",
  },
  {
    id: 17,
    term: "plausible",
    definition: "Seeming reasonable or likely",
    status: "learned",
  },
  {
    id: 18,
    term: "subtle",
    definition: "Not obvious or easy to notice",
    status: "learned",
  },
  {
    id: 19,
    term: "coherent",
    definition: "Logical and consistent",
    status: "learned",
  },
  {
    id: 20,
    term: "versatile",
    definition: "Able to serve many purposes",
    status: "learned",
  },
  {
    id: 21,
    term: "profound",
    definition: "Deep or very meaningful",
    status: "learned",
  },
  {
    id: 22,
    term: "vivid",
    definition: "Clear, detailed, and lifelike",
    status: "learned",
  },
  {
    id: 23,
    term: "foster",
    definition: "Encourage growth or development",
    status: "learned",
  },
  {
    id: 24,
    term: "diligent",
    definition: "Careful and hardworking",
    status: "learned",
  },
  {
    id: 25,
    term: "compelling",
    definition: "Convincing and engaging",
    status: "learned",
  },
];
