alter table memento.vocabulary_items
  drop constraint vocabulary_items_status_check;

update memento.vocabulary_items
set status = 'practicing', updated_at = now()
where status = 'learned'
  and app_id = 'en';

alter table memento.vocabulary_items
  add constraint vocabulary_items_status_check
  check (status in ('learning', 'practicing', 'learned'));

create table memento.speaking_states (
  vocabulary_id bigint primary key
    references memento.vocabulary_items (id) on delete cascade,
  practice_rank bigint not null,
  correct_uses integer not null default 0 check (correct_uses >= 0),
  incorrect_uses integer not null default 0 check (incorrect_uses >= 0),
  missed integer not null default 0 check (missed >= 0),
  first_seen_at timestamptz,
  last_seen_at timestamptz,
  last_used_at timestamptz,
  updated_at timestamptz not null default now()
);

insert into memento.speaking_states (vocabulary_id, practice_rank)
select id,
  row_number() over (partition by user_id, app_id order by created_at, id) * 1024
from memento.vocabulary_items
where app_id = 'en' and status = 'practicing' and not is_removed;

create table memento.speaking_tasks (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null,
  app_id text not null,
  task_date date not null,
  status text not null
    check (status in ('preparing', 'ready', 'active', 'completed', 'failed')),
  topic text,
  domain text,
  grammar_focus text,
  prompt text,
  created_at timestamptz not null default now(),
  ready_at timestamptz,
  activated_at timestamptz,
  completed_at timestamptz,
  foreign key (user_id, app_id)
    references memento.user_apps (user_id, app_id) on delete cascade
);

create table memento.speaking_task_items (
  task_id uuid not null references memento.speaking_tasks (id) on delete cascade,
  vocabulary_id bigint not null references memento.vocabulary_items (id),
  position integer not null check (position between 0 and 2),
  term_snapshot text not null,
  definition_snapshot text not null,
  primary key (task_id, vocabulary_id),
  unique (task_id, position)
);

create table memento.speaking_task_messages (
  chat_id bigint not null,
  message_id bigint not null,
  task_id uuid not null references memento.speaking_tasks (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (chat_id, message_id)
);

create table memento.speaking_lessons (
  id bigint generated by default as identity primary key,
  task_id uuid not null unique references memento.speaking_tasks (id),
  chat_id bigint not null,
  message_id bigint not null,
  transcript text,
  transcript_expires_at timestamptz,
  speech_stats jsonb not null default '{}'::jsonb,
  evaluation jsonb not null default '{}'::jsonb,
  feedback_html text not null,
  created_at timestamptz not null default now(),
  unique (chat_id, message_id)
);

create table memento.pending_resets (
  user_id bigint not null,
  app_id text not null,
  learning_count integer not null check (learning_count >= 0),
  has_open_task boolean not null,
  requested_at timestamptz not null,
  expires_at timestamptz not null,
  primary key (user_id, app_id),
  foreign key (user_id, app_id)
    references memento.user_apps (user_id, app_id) on delete cascade
);

create index speaking_states_practice_rank_idx
  on memento.speaking_states (practice_rank);
create index speaking_tasks_user_app_date_idx
  on memento.speaking_tasks (user_id, app_id, task_date, created_at desc);
create unique index speaking_tasks_one_open_per_user_app_idx
  on memento.speaking_tasks (user_id, app_id)
  where status in ('preparing', 'ready', 'active');
create index speaking_lessons_transcript_expiry_idx
  on memento.speaking_lessons (transcript_expires_at)
  where transcript is not null;

alter table memento.speaking_states enable row level security;
alter table memento.speaking_tasks enable row level security;
alter table memento.speaking_task_items enable row level security;
alter table memento.speaking_task_messages enable row level security;
alter table memento.speaking_lessons enable row level security;
alter table memento.pending_resets enable row level security;

revoke all on table memento.speaking_states from public, anon, authenticated;
revoke all on table memento.speaking_tasks from public, anon, authenticated;
revoke all on table memento.speaking_task_items from public, anon, authenticated;
revoke all on table memento.speaking_task_messages from public, anon, authenticated;
revoke all on table memento.speaking_lessons from public, anon, authenticated;
revoke all on table memento.pending_resets from public, anon, authenticated;
grant select, insert, update, delete on table memento.speaking_states to service_role;
grant select, insert, update, delete on table memento.speaking_tasks to service_role;
grant select, insert, update, delete on table memento.speaking_task_items to service_role;
grant select, insert, update, delete on table memento.speaking_task_messages to service_role;
grant select, insert, update, delete on table memento.speaking_lessons to service_role;
grant select, insert, update, delete on table memento.pending_resets to service_role;
grant usage, select on all sequences in schema memento to service_role;

create or replace function memento.promote_vocabulary_to_practicing(
  requested_vocabulary_id bigint,
  requested_user_id bigint,
  requested_app_id text,
  promoted_at timestamptz default now()
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target memento.vocabulary_items%rowtype;
  next_rank bigint;
begin
  select * into target
  from memento.vocabulary_items
  where id = requested_vocabulary_id
    and user_id = requested_user_id
    and app_id = requested_app_id
    and not is_removed
  for update;

  if not found then raise exception 'VOCABULARY_NOT_FOUND'; end if;
  if target.status = 'learned' then return false; end if;
  if target.status = 'practicing' then return true; end if;

  select coalesce(max(state.practice_rank), 0) + 1024 into next_rank
  from memento.speaking_states state
  join memento.vocabulary_items item on item.id = state.vocabulary_id
  where item.user_id = requested_user_id
    and item.app_id = requested_app_id
    and item.status = 'practicing'
    and not item.is_removed;

  insert into memento.speaking_states (vocabulary_id, practice_rank, updated_at)
  values (target.id, next_rank, promoted_at)
  on conflict (vocabulary_id) do update
    set practice_rank = excluded.practice_rank,
        correct_uses = 0,
        incorrect_uses = 0,
        missed = 0,
        first_seen_at = null,
        last_seen_at = null,
        last_used_at = null,
        updated_at = promoted_at;

  update memento.vocabulary_items
  set status = 'practicing', updated_at = promoted_at
  where id = target.id;
  return true;
end;
$$;

create or replace function memento.prepare_learning_reset(
  requested_user_id bigint,
  requested_app_id text,
  requested_at timestamptz default now()
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  item_count integer;
  open_task boolean;
begin
  perform 1 from memento.user_apps
  where user_id = requested_user_id and app_id = requested_app_id
  for update;
  if not found then raise exception 'USER_NOT_FOUND'; end if;

  select count(*) into item_count
  from memento.vocabulary_items
  where user_id = requested_user_id and app_id = requested_app_id
    and status = 'learning' and not is_removed;

  select exists (
    select 1 from memento.speaking_tasks
    where user_id = requested_user_id and app_id = requested_app_id
      and status in ('preparing', 'ready', 'active')
  ) into open_task;

  insert into memento.pending_resets (
    user_id, app_id, learning_count, has_open_task, requested_at, expires_at
  ) values (
    requested_user_id, requested_app_id, item_count, open_task,
    requested_at, requested_at + interval '10 minutes'
  ) on conflict (user_id, app_id) do update
    set learning_count = excluded.learning_count,
        has_open_task = excluded.has_open_task,
        requested_at = excluded.requested_at,
        expires_at = excluded.expires_at;

  return jsonb_build_object('learningCount', item_count, 'hasOpenTask', open_task);
end;
$$;

create or replace function memento.restore_vocabulary_to_practicing(
  requested_vocabulary_id bigint,
  requested_user_id bigint,
  requested_app_id text,
  restored_at timestamptz default now()
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target memento.vocabulary_items%rowtype;
  next_rank bigint;
begin
  select * into target
  from memento.vocabulary_items
  where id = requested_vocabulary_id
    and user_id = requested_user_id
    and app_id = requested_app_id
    and not is_removed
  for update;
  if not found then raise exception 'VOCABULARY_NOT_FOUND'; end if;
  if target.status <> 'learned' then return false; end if;

  select coalesce(max(state.practice_rank), 0) + 1024 into next_rank
  from memento.speaking_states state
  join memento.vocabulary_items item on item.id = state.vocabulary_id
  where item.user_id = requested_user_id
    and item.app_id = requested_app_id
    and item.status = 'practicing'
    and not item.is_removed;

  insert into memento.speaking_states (vocabulary_id, practice_rank, updated_at)
  values (target.id, next_rank, restored_at)
  on conflict (vocabulary_id) do update
    set practice_rank = excluded.practice_rank,
        correct_uses = 0,
        incorrect_uses = 0,
        missed = 0,
        first_seen_at = null,
        last_seen_at = null,
        last_used_at = null,
        updated_at = restored_at;

  update memento.vocabulary_items
  set status = 'practicing', updated_at = restored_at
  where id = target.id;
  return true;
end;
$$;

create or replace function memento.confirm_learning_reset(
  requested_user_id bigint,
  requested_app_id text,
  confirmed_at timestamptz default now()
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  pending memento.pending_resets%rowtype;
  removed_count integer;
  removed_task_count integer;
begin
  select * into pending from memento.pending_resets
  where user_id = requested_user_id and app_id = requested_app_id
  for update;
  if not found or pending.expires_at < confirmed_at then
    delete from memento.pending_resets
    where user_id = requested_user_id and app_id = requested_app_id;
    raise exception 'RESET_CONFIRMATION_EXPIRED';
  end if;

  update memento.rounds
  set status = 'cancelled', completed_at = confirmed_at
  where user_id = requested_user_id and app_id = requested_app_id
    and status in ('preparing', 'active');

  update memento.vocabulary_items
  set is_removed = true, updated_at = confirmed_at
  where user_id = requested_user_id and app_id = requested_app_id
    and status = 'learning' and not is_removed;
  get diagnostics removed_count = row_count;

  delete from memento.speaking_tasks
  where user_id = requested_user_id and app_id = requested_app_id
    and status in ('preparing', 'ready', 'active');
  get diagnostics removed_task_count = row_count;

  delete from memento.pending_resets
  where user_id = requested_user_id and app_id = requested_app_id;

  return jsonb_build_object(
    'learningCount', removed_count,
    'taskCancelled', removed_task_count > 0
  );
end;
$$;

create or replace function memento.complete_speaking_task(
  requested_task_id uuid,
  requested_user_id bigint,
  requested_app_id text,
  incoming_chat_id bigint,
  incoming_message_id bigint,
  requested_transcript text,
  requested_speech_stats jsonb,
  requested_evaluation jsonb,
  requested_feedback_html text,
  finished_at timestamptz default now()
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_task memento.speaking_tasks%rowtype;
  usage_record record;
  new_correct integer;
  next_rank bigint;
begin
  select * into target_task from memento.speaking_tasks
  where id = requested_task_id
    and user_id = requested_user_id
    and app_id = requested_app_id
  for update;
  if not found then raise exception 'TASK_NOT_FOUND'; end if;
  if target_task.status = 'completed' then
    return jsonb_build_object('alreadyCompleted', true);
  end if;
  if target_task.status <> 'active' then raise exception 'TASK_STALE'; end if;
  if jsonb_typeof(requested_evaluation->'requiredPhraseUsage') <> 'array' then
    raise exception 'INVALID_EVALUATION';
  end if;

  if (
    select count(*) from jsonb_to_recordset(requested_evaluation->'requiredPhraseUsage')
      as usage("vocabularyId" text, status text)
  ) <> (
    select count(*) from memento.speaking_task_items where task_id = requested_task_id
  ) then raise exception 'INVALID_EVALUATION'; end if;

  insert into memento.speaking_lessons (
    task_id, chat_id, message_id, transcript, transcript_expires_at,
    speech_stats, evaluation, feedback_html, created_at
  ) values (
    requested_task_id, incoming_chat_id, incoming_message_id,
    requested_transcript, finished_at + interval '30 days',
    coalesce(requested_speech_stats, '{}'::jsonb),
    coalesce(requested_evaluation, '{}'::jsonb),
    requested_feedback_html, finished_at
  );

  select coalesce(max(state.practice_rank), 0) into next_rank
  from memento.speaking_states state
  join memento.vocabulary_items item on item.id = state.vocabulary_id
  where item.user_id = requested_user_id
    and item.app_id = requested_app_id
    and item.status = 'practicing'
    and not item.is_removed;

  for usage_record in
    select item.vocabulary_id,
      coalesce(usage.status, 'missed') as status
    from memento.speaking_task_items item
    left join jsonb_to_recordset(requested_evaluation->'requiredPhraseUsage')
      as usage("vocabularyId" text, status text)
      on usage."vocabularyId" = item.vocabulary_id::text
    where item.task_id = requested_task_id
  loop
    next_rank := next_rank + 1024;
    update memento.speaking_states
    set practice_rank = next_rank,
        correct_uses = correct_uses + case when usage_record.status = 'used_correctly' then 1 else 0 end,
        incorrect_uses = incorrect_uses + case when usage_record.status = 'used_incorrectly' then 1 else 0 end,
        missed = missed + case when usage_record.status = 'missed' then 1 else 0 end,
        first_seen_at = coalesce(first_seen_at, finished_at),
        last_seen_at = finished_at,
        last_used_at = case when usage_record.status = 'used_correctly' then finished_at else last_used_at end,
        updated_at = finished_at
    where vocabulary_id = usage_record.vocabulary_id
    returning correct_uses into new_correct;

    if new_correct >= 3 then
      update memento.vocabulary_items
      set status = 'learned', updated_at = finished_at
      where id = usage_record.vocabulary_id
        and user_id = requested_user_id and app_id = requested_app_id
        and status = 'practicing' and not is_removed;
    end if;
  end loop;

  update memento.speaking_tasks
  set status = 'completed', completed_at = finished_at
  where id = requested_task_id;

  return jsonb_build_object('alreadyCompleted', false);
end;
$$;

create or replace function memento.purge_expired_speaking_transcripts(
  purged_at timestamptz default now()
) returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  purged_count integer;
begin
  update memento.speaking_lessons
  set transcript = null,
      transcript_expires_at = null,
      feedback_html = coalesce(evaluation->>'telegramFeedback', ''),
      evaluation = jsonb_set(
        jsonb_set(
          evaluation,
          '{corrections}',
          coalesce(
            (select jsonb_agg(value - 'original')
             from jsonb_array_elements(coalesce(evaluation->'corrections', '[]'::jsonb))),
            '[]'::jsonb
          )
        ),
        '{requiredPhraseUsage}',
        coalesce(
          (select jsonb_agg(value - 'evidence')
           from jsonb_array_elements(coalesce(evaluation->'requiredPhraseUsage', '[]'::jsonb))),
          '[]'::jsonb
        )
      )
  where transcript is not null
    and transcript_expires_at <= purged_at;
  get diagnostics purged_count = row_count;
  return purged_count;
end;
$$;

-- Quiz mastery now graduates into productive speaking practice.
create or replace function memento.complete_round(
  requested_round_id uuid,
  requested_user_id bigint,
  first_attempt_results jsonb,
  requested_mistakes integer,
  reviewed_at timestamptz default now()
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_round memento.rounds%rowtype;
  result_record record;
  state_record memento.scheduling_states%rowtype;
  new_repetitions integer;
  new_consecutive integer;
  new_interval integer;
  new_ease numeric(4, 2);
  correct_count integer := 0;
begin
  select * into target_round from memento.rounds
  where id = requested_round_id and user_id = requested_user_id for update;
  if not found then raise exception 'ROUND_NOT_FOUND'; end if;
  if target_round.status = 'succeeded' then
    return jsonb_build_object('alreadyCompleted', true);
  end if;
  if target_round.status <> 'active' then raise exception 'ROUND_STALE'; end if;
  if jsonb_typeof(first_attempt_results) <> 'array'
     or jsonb_array_length(first_attempt_results) <> target_round.total_items
     or requested_mistakes < 0 or requested_mistakes > 2 then
    raise exception 'INVALID_RESULTS';
  end if;
  if exists (
    select 1 from jsonb_to_recordset(first_attempt_results) as r(vocabulary_id bigint, correct boolean)
    where not (r.vocabulary_id = any(target_round.selected_vocabulary_ids))
  ) or (
    select count(distinct r.vocabulary_id)
    from jsonb_to_recordset(first_attempt_results) as r(vocabulary_id bigint, correct boolean)
  ) <> target_round.total_items then raise exception 'INVALID_RESULTS'; end if;
  if exists (
    select 1 from memento.vocabulary_items v
    where v.id = any(target_round.selected_vocabulary_ids)
      and (v.user_id <> requested_user_id or v.app_id <> target_round.app_id
        or v.status <> 'learning' or v.is_removed)
  ) then raise exception 'ROUND_STALE'; end if;

  for result_record in
    select * from jsonb_to_recordset(first_attempt_results)
      as r(vocabulary_id bigint, correct boolean)
  loop
    select * into state_record from memento.scheduling_states
    where vocabulary_id = result_record.vocabulary_id for update;
    if result_record.correct then
      correct_count := correct_count + 1;
      new_repetitions := state_record.repetitions + 1;
      new_consecutive := state_record.consecutive_correct + 1;
      new_ease := greatest(1.30, state_record.ease_factor + 0.10);
      new_interval := case when new_repetitions = 1 then 1
        when new_repetitions = 2 then 6
        else greatest(1, round(state_record.interval_days * new_ease)::integer) end;
    else
      new_repetitions := 0;
      new_consecutive := 0;
      new_ease := greatest(1.30, state_record.ease_factor - 0.20);
      new_interval := 1;
    end if;
    update memento.scheduling_states
    set repetitions = new_repetitions, consecutive_correct = new_consecutive,
        interval_days = new_interval, ease_factor = new_ease,
        next_review_at = reviewed_at + make_interval(days => new_interval),
        last_reviewed_at = reviewed_at, updated_at = reviewed_at
    where vocabulary_id = result_record.vocabulary_id;
    if new_consecutive >= 3 and new_interval >= 14 then
      if target_round.app_id = 'en' then
        perform memento.promote_vocabulary_to_practicing(
          result_record.vocabulary_id, requested_user_id, target_round.app_id, reviewed_at
        );
      else
        update memento.vocabulary_items
        set status = 'learned', updated_at = reviewed_at
        where id = result_record.vocabulary_id;
      end if;
    end if;
  end loop;

  update memento.rounds
  set status = 'succeeded', first_attempt_correct = correct_count,
      mistakes = requested_mistakes, completed_at = reviewed_at
  where id = requested_round_id;
  return jsonb_build_object('alreadyCompleted', false,
    'firstAttemptCorrect', correct_count, 'total', target_round.total_items);
end;
$$;

revoke all on function memento.promote_vocabulary_to_practicing(bigint, bigint, text, timestamptz)
  from public, anon, authenticated;
revoke all on function memento.restore_vocabulary_to_practicing(bigint, bigint, text, timestamptz)
  from public, anon, authenticated;
revoke all on function memento.prepare_learning_reset(bigint, text, timestamptz)
  from public, anon, authenticated;
revoke all on function memento.confirm_learning_reset(bigint, text, timestamptz)
  from public, anon, authenticated;
revoke all on function memento.complete_speaking_task(uuid, bigint, text, bigint, bigint, text, jsonb, jsonb, text, timestamptz)
  from public, anon, authenticated;
revoke all on function memento.purge_expired_speaking_transcripts(timestamptz)
  from public, anon, authenticated;
grant execute on function memento.promote_vocabulary_to_practicing(bigint, bigint, text, timestamptz)
  to service_role;
grant execute on function memento.restore_vocabulary_to_practicing(bigint, bigint, text, timestamptz)
  to service_role;
grant execute on function memento.prepare_learning_reset(bigint, text, timestamptz)
  to service_role;
grant execute on function memento.confirm_learning_reset(bigint, text, timestamptz)
  to service_role;
grant execute on function memento.complete_speaking_task(uuid, bigint, text, bigint, bigint, text, jsonb, jsonb, text, timestamptz)
  to service_role;
grant execute on function memento.purge_expired_speaking_transcripts(timestamptz)
  to service_role;

-- The previous destructive reset RPC remains in migration history, but the app
-- now exposes only the confirmed Learning-scoped reset workflow.
revoke execute on function memento.reset_vocabulary(bigint) from service_role;
revoke execute on function memento.reset_vocabulary(bigint, text) from service_role;
