create extension if not exists pgcrypto;

create schema if not exists memento;
revoke all on schema memento from public, anon, authenticated;
grant usage on schema memento to service_role;

-- Keep the shared project's existing API schemas and expose only Memento's
-- isolated schema in addition to them.
alter role authenticator set pgrst.db_schemas = 'public, graphql_public, memento';
notify pgrst, 'reload config';

create table memento.app_users (
  telegram_user_id bigint primary key check (telegram_user_id > 0),
  username text,
  first_name text,
  last_name text,
  starter_seeded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table memento.vocabulary_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references memento.app_users (telegram_user_id) on delete cascade,
  term text not null check (char_length(btrim(term)) between 1 and 200),
  normalized_term text generated always as (lower(btrim(term))) stored,
  definition text not null check (char_length(btrim(definition)) between 1 and 500),
  status text not null default 'learning' check (status in ('learning', 'learned')),
  is_removed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, normalized_term)
);

create table memento.scheduling_states (
  vocabulary_id bigint primary key references memento.vocabulary_items (id) on delete cascade,
  repetitions integer not null default 0 check (repetitions >= 0),
  consecutive_correct integer not null default 0 check (consecutive_correct >= 0),
  interval_days integer not null default 0 check (interval_days >= 0),
  ease_factor numeric(4, 2) not null default 2.50 check (ease_factor >= 1.30),
  next_review_at timestamptz,
  last_reviewed_at timestamptz,
  updated_at timestamptz not null default now()
);

create table memento.rounds (
  id uuid primary key default gen_random_uuid(),
  user_id bigint not null references memento.app_users (telegram_user_id) on delete cascade,
  status text not null check (status in ('preparing', 'active', 'succeeded', 'failed', 'cancelled')),
  selected_vocabulary_ids bigint[] not null,
  total_items integer not null check (total_items between 1 and 10),
  first_attempt_correct integer,
  mistakes integer,
  created_at timestamptz not null default now(),
  activated_at timestamptz,
  completed_at timestamptz
);

create table memento.round_cards (
  id bigint generated by default as identity primary key,
  round_id uuid not null references memento.rounds (id) on delete cascade,
  vocabulary_id bigint not null references memento.vocabulary_items (id),
  position integer not null check (position >= 0),
  sentence text not null,
  answer text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array' and jsonb_array_length(options) = 4),
  created_at timestamptz not null default now(),
  unique (round_id, vocabulary_id),
  unique (round_id, position)
);

create table memento.generation_usage (
  user_id bigint not null references memento.app_users (telegram_user_id) on delete cascade,
  usage_date date not null,
  attempts integer not null default 0 check (attempts between 0 and 5),
  updated_at timestamptz not null default now(),
  primary key (user_id, usage_date)
);

create index vocabulary_items_user_status_idx
  on memento.vocabulary_items (user_id, status, is_removed);
create index scheduling_states_due_idx
  on memento.scheduling_states (next_review_at)
  where next_review_at is not null;
create index rounds_user_created_idx
  on memento.rounds (user_id, created_at desc);
create index round_cards_round_idx on memento.round_cards (round_id);
create unique index rounds_one_open_per_user_idx
  on memento.rounds (user_id)
  where status in ('preparing', 'active');

alter table memento.app_users enable row level security;
alter table memento.vocabulary_items enable row level security;
alter table memento.scheduling_states enable row level security;
alter table memento.rounds enable row level security;
alter table memento.round_cards enable row level security;
alter table memento.generation_usage enable row level security;

revoke all on table memento.app_users from anon, authenticated;
revoke all on table memento.vocabulary_items from anon, authenticated;
revoke all on table memento.scheduling_states from anon, authenticated;
revoke all on table memento.rounds from anon, authenticated;
revoke all on table memento.round_cards from anon, authenticated;
revoke all on table memento.generation_usage from anon, authenticated;
revoke usage, select on all sequences in schema memento from anon, authenticated;
grant select, insert, update, delete on all tables in schema memento to service_role;
grant usage, select on all sequences in schema memento to service_role;

create or replace function memento.reserve_generation_attempt(
  requested_user_id bigint,
  requested_date date
) returns boolean
language plpgsql
security invoker
set search_path = ''
as $$
declare
  next_attempts integer;
begin
  insert into memento.generation_usage (user_id, usage_date, attempts)
  values (requested_user_id, requested_date, 1)
  on conflict (user_id, usage_date) do update
    set attempts = memento.generation_usage.attempts + 1,
        updated_at = now()
    where memento.generation_usage.attempts < 5
  returning attempts into next_attempts;

  return next_attempts is not null;
end;
$$;

create or replace function memento.complete_round(
  requested_round_id uuid,
  requested_user_id bigint,
  first_attempt_results jsonb,
  requested_mistakes integer,
  reviewed_at timestamptz default now()
) returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_round memento.rounds%rowtype;
  result_record record;
  state_record memento.scheduling_states%rowtype;
  new_repetitions integer;
  new_consecutive integer;
  new_interval integer;
  new_ease numeric(4, 2);
  correct_count integer := 0;
begin
  select * into target_round
  from memento.rounds
  where id = requested_round_id and user_id = requested_user_id
  for update;

  if not found then
    raise exception 'ROUND_NOT_FOUND';
  end if;
  if target_round.status = 'succeeded' then
    return jsonb_build_object('alreadyCompleted', true);
  end if;
  if target_round.status <> 'active' then
    raise exception 'ROUND_STALE';
  end if;
  if jsonb_typeof(first_attempt_results) <> 'array'
     or jsonb_array_length(first_attempt_results) <> target_round.total_items then
    raise exception 'INVALID_RESULTS';
  end if;
  if requested_mistakes < 0 or requested_mistakes > 2 then
    raise exception 'INVALID_RESULTS';
  end if;
  if exists (
    select 1
    from jsonb_to_recordset(first_attempt_results) as r(vocabulary_id bigint, correct boolean)
    where not (r.vocabulary_id = any(target_round.selected_vocabulary_ids))
  ) or (
    select count(distinct r.vocabulary_id)
    from jsonb_to_recordset(first_attempt_results) as r(vocabulary_id bigint, correct boolean)
  ) <> target_round.total_items then
    raise exception 'INVALID_RESULTS';
  end if;
  if exists (
    select 1
    from memento.vocabulary_items v
    where v.id = any(target_round.selected_vocabulary_ids)
      and (v.user_id <> requested_user_id or v.status <> 'learning' or v.is_removed)
  ) then
    raise exception 'ROUND_STALE';
  end if;

  for result_record in
    select * from jsonb_to_recordset(first_attempt_results)
      as r(vocabulary_id bigint, correct boolean)
  loop
    select * into state_record
    from memento.scheduling_states
    where vocabulary_id = result_record.vocabulary_id
    for update;

    if result_record.correct then
      correct_count := correct_count + 1;
      new_repetitions := state_record.repetitions + 1;
      new_consecutive := state_record.consecutive_correct + 1;
      new_ease := greatest(1.30, state_record.ease_factor + 0.10);
      new_interval := case
        when new_repetitions = 1 then 1
        when new_repetitions = 2 then 6
        else greatest(1, round(state_record.interval_days * new_ease)::integer)
      end;
    else
      new_repetitions := 0;
      new_consecutive := 0;
      new_ease := greatest(1.30, state_record.ease_factor - 0.20);
      new_interval := 1;
    end if;

    update memento.scheduling_states
    set repetitions = new_repetitions,
        consecutive_correct = new_consecutive,
        interval_days = new_interval,
        ease_factor = new_ease,
        next_review_at = reviewed_at + make_interval(days => new_interval),
        last_reviewed_at = reviewed_at,
        updated_at = reviewed_at
    where vocabulary_id = result_record.vocabulary_id;

    if new_consecutive >= 3 and new_interval >= 14 then
      update memento.vocabulary_items
      set status = 'learned', updated_at = reviewed_at
      where id = result_record.vocabulary_id;
    end if;
  end loop;

  update memento.rounds
  set status = 'succeeded',
      first_attempt_correct = correct_count,
      mistakes = requested_mistakes,
      completed_at = reviewed_at
  where id = requested_round_id;

  return jsonb_build_object(
    'alreadyCompleted', false,
    'firstAttemptCorrect', correct_count,
    'total', target_round.total_items
  );
end;
$$;

revoke all on function memento.reserve_generation_attempt(bigint, date) from public, anon, authenticated;
revoke all on function memento.complete_round(uuid, bigint, jsonb, integer, timestamptz) from public, anon, authenticated;
grant execute on function memento.reserve_generation_attempt(bigint, date) to service_role;
grant execute on function memento.complete_round(uuid, bigint, jsonb, integer, timestamptz) to service_role;
